AWSTemplateFormatVersion: "2010-09-09"
Description: A Sampple template for VPC
Parameters:
  Cidr:
    Description: Specify a CIDR range
    Type: String
    Default: 10.0.0.0/16
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref Cidr
      EnableDnsSupport: true
